require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'RNGamerMVVM' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  # Usa frameworks con enlace estático
  use_frameworks!({
    :linkage => :static
  })

  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, # Hermes habilitado por defecto
    :fabric_enabled => flags[:fabric_enabled],
    #:flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RNGamerMVVMTests' do
    inherit! :complete
    # Pods para pruebas
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false # Cambiar a true si usas Mac Catalyst
    )
  
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
    end
  
    # Aplicar workaround para Xcode 12.5 y M1/M3
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end
